### ISSUE TITLE
restic to minio:sia backend panic runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mannp** [restic/restic#1204]
Noob restic user here :) testing with a PR version being worked on by @dvstate (https://github.com/dvstate/minio/) for sia/minio to allow a sia backend.

Appreciate I am using a PR version of minio with sia, but I wanted to give a heads up to my issue, incase it was a bug in restic only.

I am using restic 0.7.1 compiled with go1.9 on darwin/amd64

I have successfully initialised the repo (using the latest PR) and have now tried to backup 1 file with the following command;
```
restic -r s3:http://192.168.1.99:9001/restic backup /Users/local/Test
enter password for repository:
```
I get the following panic;

> panic:

```
 runtime error: slice bounds out of range

goroutine

 1 [running]:
restic/repository.SearchKey(0x185a7c0, 0xc4200140c8, 0xc420114c60, 0xc42015c240, 0x40, 0x14, 0x40, 0xc42015c240, 0x40)
	src/restic/repository/key.go:126 +0x461
restic/repository.(*Repository).SearchKey(0xc420114c60, 0x185a7c0, 0xc4200140c8, 0xc42015c240, 0x40, 0x14, 0xc420134900, 0x0)
	src/restic/repository/repository.go:369 +0x84
main.OpenRepository(0x7ffeefbffb5a, 0x22, 0x0, 0x0, 0x0, 0x185a780, 0xc420134900, 0xc42015c240, 0x40, 0x1853fc0, ...)
	src/cmds/restic/global.go:313 +0xf0
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/cmds/restic/cmd_backup.go:365 +0x447
main.glob..func2(0x188e2a0, 0xc42011b2f0, 0x1, 0x3, 0x0, 0x0)
	src/cmds/restic/cmd_backup.go:39 +0x1b9
github.com/spf13/cobra.(*Command).execute(0x188e2a0, 0xc420134a40, 0x3, 0x4, 0x188e2a0, 0xc420134a40)
	src/github.com/spf13/cobra/command.go:647 +0x3f1
github.com/spf13/cobra.(*Command).ExecuteC(0x188de60, 0x1028fa6, 0x15e4518, 0xc4201a3de8)
	src/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/spf13/cobra.(*Command).Execute(0x188de60, 0x24, 0xc4201a3eb0)
	src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	src/cmds/restic/main.go:63 +0x1de
```

**Comment by fd0** [comment]
Hm, it looks like there's a file in the repo that restic does not expect. It should not print a stacktrace though. Can you please create a debug log? Instructions are here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by mannp** [comment]
Unfortunately I cannot get it to produce a log.

It continues to produce the error each time though.

**Comment by fd0** [comment]
What did you do? Did you recompile restic as instructed, and set the environment variable?

**Comment by mannp** [comment]
Set the ENV variable but didn't expect to have to build a dev environment to add logging.

It will have to wait, as I don't have the dependencies installed.

I will wait until the PR gets merged into minio before more testing, as it could just be wasting both of our time.

**Comment by fd0** [comment]
Okay, thanks for your effort so far. Please know that compiling restic is really easy, and you just need a (rather recent) version of Go (>= 1.8) to build it, nothing more.

I'm looking forward to a debug log so that we can see what's going on :)

**Comment by fd0** [comment]
Hey, thanks a lot for the report, it's an embarrassingly simple bug. The cause is that the server's list of files in the `keys` directory includes a file with a filename  with less than 12 characters, which is invalid for a restic key file. It'll be resolved in the master branch later today when #1220 is merged.

**Comment by mannp** [comment]
Out of interest, why would that file have been created, as it was purely a restic repo.

Unless it was some OS crud that gets added by default.

**Comment by fd0** [comment]
It wouldn't have. Restic does not create any files with short names. hm. Can you have a look what's in the `keys/` directory?

**Comment by mannp** [comment]
There is a long (is it 64 chars?) key looking set of characters and that is it....

I have build the latest restic source and tested again and it still crashed with the same error :(

It is using the new code as it now accepts the new command line arguments you have added.

Shall I do another log....

**Comment by mannp** [comment]
Not sure why but found .fuse_hidden0237f0170000ccf7 in the keys directory just now.

If I delete it another reappears with a different number...

**Comment by fd0** [comment]
I've got no idea how that file ended up there, but I'll try to reproduce the panic now.

**Comment by fd0** [comment]
Hm. There's definitely a bug, but I don't see a panic any more. Can you please paste the stack trace?

**Comment by mannp** [comment]
@fd0 Thanks for taking another look so quickly.

Is the stack trace more than the second log I posted above?

Here is the 3rd log, as I have pulled the master branch again and rebuilt with debug and this is the new log;

[http://safe.dsh.re/download/b2faf359-e515-4a1a-b141-b27835b2e7a1](log)

**Comment by fd0** [comment]
I've just merged my fix, should work now with the code in the `master` branch.

If it still does not work, the complete output of the `restic backup` run is probably sufficient.

**Comment by mannp** [comment]
Mac:restic local$ git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/restic/restic
   6f8eba9c..1a08a821  master     -> origin/master
Updating 6f8eba9c..1a08a821
Fast-forward
 cmd/restic/global.go            | 2 +-
 internal/repository/key.go      | 9 ++++++---
 internal/repository/parallel.go | 2 +-
 3 files changed, 8 insertions(+), 5 deletions(-)

Mac:restic local$ export DEBUG_LOG=/Users/local/Desktop/restic-debugv4.log

Mac:restic local$ go run build.go -tags debug

Mac:restic local$ ./restic -r s3:http://192.168.1.99:9001/rbackup backup /Users/local/Test
debug log file /Users/local/Desktop/restic-debugv4.log
debug enabled
enter password for repository:
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/restic/restic/internal/repository.OpenKey(0x1ab0000, 0xc4200140b8, 0xc42030c0c0, 0xc4202d4217, 0x6, 0xc420244ec0, 0x40, 0x1, 0xc4201d3498, 0x10711db)
	src/github.com/restic/restic/internal/repository/key.go:69 +0x6cf
github.com/restic/restic/internal/repository.SearchKey(0x1ab0000, 0xc4200140b8, 0xc42030c0c0, 0xc420244ec0, 0x40, 0x14, 0x15b9d79, 0x0, 0xc420244e80)
	src/github.com/restic/restic/internal/repository/key.go:127 +0x1ee
github.com/restic/restic/internal/repository.(*Repository).SearchKey(0xc42030c0c0, 0x1ab0000, 0xc4200140b8, 0xc420244ec0, 0x40, 0x14, 0xc420116640, 0x0)
	src/github.com/restic/restic/internal/repository/repository.go:369 +0x84
main.OpenRepository(0x7ffeefbffacc, 0x23, 0x0, 0x0, 0x0, 0x1aaffc0, 0xc420116640, 0xc420244ec0, 0x40, 0x1aa8b00, ...)
	src/github.com/restic/restic/cmd/restic/global.go:320 +0x16c
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:375 +0x417
main.glob..func3(0x1ae6b80, 0xc420202630, 0x1, 0x3, 0x0, 0x0)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:51 +0x19f
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute(0x1ae6b80, 0xc420116800, 0x3, 0x4, 0x1ae6b80, 0xc420116800)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:649 +0x456
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ae6700, 0xc420118258, 0x16387e0, 0xc420220340)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ae6700, 0x25, 0xc4201d3eb0)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	src/github.com/restic/restic/cmd/restic/main.go:69 +0x1f9

**Comment by fd0** [comment]
Oh, that's another bug. Please see #1228.

**Comment by mannp** [comment]
Some progress :) thanks for your patience!

> We encountered an internal error, please try again.

[http://safe.dsh.re/download/eb30a7be-2142-4271-a6ce-4d96bfd4a901](log)

**Comment by fd0** [comment]
That's a server side error. Is there anything in the server's log?

**Comment by mannp** [comment]
Multiple of the same message, that seem to be there all of the time....

time="2017-09-10T16:29:44+01:00" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]"

time="2017-09-10T16:29:44+01:00" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]"

time="2017-09-10T16:29:45+01:00" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]"

time="2017-09-10T16:29:48+01:00" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]"

time="2017-09-10T16:29:54+01:00" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]"

**Comment by fd0** [comment]
That's not an issue in restic any more... Sorry.

**Comment by mannp** [comment]
I've updated the sia-minio original issue for @dvstate to look at.

**Comment by chrsch** [comment]
@mannp Did you ever resolve the "Failed to select records in the cache database" error above?

**Comment by mannp** [comment]
@chrsch The last iteration of the sia gateway code that was merged into minio didn't include support for multipart transfers so it didn't work for me with restic at all; so I stopped using sia tbh.
