### ISSUE TITLE
"restic dump" command fails on 0.9.5; succeeds with 0.9.4

### ISSUE THREAD

**Issue by cdhowie** [restic/restic#2357]
Output of `restic version`
--------------------------
```
restic 0.9.5 compiled with go1.12.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
restic dump $snapshot /usr/local/apache2/$filepath
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local disk storage.

Expected behavior
-----------------
Restic should dump the file to standard output.

Actual behavior
---------------
Restic fails:

```
repository b01bdece opened successfully, password is correct
cannot dump file: path "/local" not found in snapshot
```

Note that the path in the error does not match the path I've asked to be dumped. The path begins with `/usr/local`, not `/local`.  On a hunch I tried `/usr/usr/local/apache2/$filepath` and this also failed, but with:

```
repository b01bdece opened successfully, password is correct
cannot dump file: path "/usr" not found in snapshot
```

Steps to reproduce the behavior
-------------------------------
I'm not sure what condition triggers the failure, but it's consistently reproducible on this 200+GB repo.

Do you have any idea what may have caused this?
-----------------------------------------------
The command works with restic 0.9.4, so I assume that some change in 0.9.5 causes this error.

**Comment by Kidswiss** [comment]
Hi @cdhowie 

Tanks for bringing this to my attention!

There are indeed a few issues with the dump command in the current version of Restic unfortunately. I tackled all of them in https://github.com/restic/restic/pull/2255, at least the ones I'm aware of. Here's the issue with some further details: https://github.com/restic/restic/issues/2254

Could you try the branch from the #2255 and see if that fixes your issues? Somehow this looks familiar and should be fixed there. But it's quite some time ago and I might be wrong about that :)

**Comment by viq** [comment]
FWIW, with `/usr/bin/restic` coming from system packages on fedora 29, `/home/user/bin/restic_v0.9.5-46-g604b18aa_linux_amd64` coming from https://beta.restic.net/restic-v0.9.5-46-g604b18aa/ and `/tmp/restic/restic` coming from https://github.com/Kidswiss/restic/tree/tar + `go run -mod=vendor build.go` (with latest go just downloaded from upstream), this is the result of trying to dump a file from backup created with the system one (wrapped in `runrestic`):
```
$ for restic in /usr/bin/restic /home/user/bin/restic_v0.9.5-46-g604b18aa_linux_amd64 /tmp/restic/restic ; do echo $restic ; $restic version ; RESTIC_PASSWORD_FILE=/rw/config/restic_pass sudo -E $restic -r /tmp/runrestic-repo-1/ dump latest /rw/home/user/Pipfile.lock | head ; done
/usr/bin/restic
restic 0.9.5 compiled with go1.11.6 on linux/amd64
cannot dump file: path "/home" not found in snapshot
/home/user/bin/restic_v0.9.5-46-g604b18aa_linux_amd64
restic 0.9.5 (v0.9.5-46-g604b18aa) compiled with go1.12.6 on linux/amd64
cannot dump file: path "/home" not found in snapshot
/tmp/restic/restic
restic 0.9.4 (v0.9.3-166-g12893fc7) compiled with go1.13.1 on linux/amd64
{
    "_meta": {
        "hash": {
            "sha256": "3a341063ab5e58c46b38c49bb925aa91bc12fc92c6245f9cd46c9746572b7d44"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
```

**Comment by Kidswiss** [comment]
@viq Thanks for testing, looks good! 

I'm still waiting for some maintainer feedback on my pull request. But I hope it'll land in the next release :)

**Comment by delanym** [comment]
Still an issue in restic 0.9.6 compiled with go1.13.4 on linux/amd64
