### ISSUE TITLE
Backup to sftp backend fails

### ISSUE THREAD

**Issue by dirk777** [restic/restic#983]
## Output of `restic version`
restic 0.6.0
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)

restic -r sftp:u1xxxxx.your-storagebox.de:/test/backup backup /Users/test/Documents

## What backend/server/service did you use?
Hetzner's and Strato's sftp backend

## Expected behavior

backup ends with
scan [/Users/test/Documents]
scanned 15 directories, 23 files in 0:00
[0:00] 100.00%  0B/s  20.254 KiB / 20.254 KiB  38 / 38 items  0 errors  ETA 0:00 
duration: 0:00, 0.02MiB/s
snapshot 9f317cfd saved

## Actual behavior

Hetzner's sftp backend:

restic -r sftp:u1xxxxx.your-storagebox.de:/test/backup backup /Users/test/Documents
enter password for repository: 
scan [/Users/test/Documents]
scanned 5255 directories, 16233 files in 0:02
subprocess ssh: packet_write_wait: Connection to 88.99.8.66 port 22: Broken pipe ETA 3:09 
panic: Close: failed to send packet header: write |1: file already closed

goroutine 89 [running]:
restic/archiver.(*Archiver).dirWorker(0xc4200e11d0, 0xc4221d2f20, 0xc420098a50, 0xc4200df260, 0xc4200df560)
	/tmp/restic-build-753916405/src/restic/archiver/archiver.go:403 +0xc7b
created by restic/archiver.(*Archiver).Snapshot
	/tmp/restic-build-753916405/src/restic/archiver/archiver.go:712 +0x67d
	
	

Strato's sftp backend:

restic -r sftp:sftp.hidrive.strato.com:/users/id-xxxx/backup/testtest backup /Users/test2/Documents
enter password for repository: 
using parent snapshot 9f317cfd
scan [/Users/test2/Documents]
scanned 15 directories, 23 files in 0:00
[0:01] 100.00%  20.254 KiB/s  20.254 KiB / 20.254 KiB  38 / 38 items  0 errors  ETA 0:00 
duration: 0:01, 0.02MiB/s
sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
OpenFile
restic/backend/sftp.(*SFTP).Save
	/tmp/restic-build-753916405/src/restic/backend/sftp/sftp.go:291
restic/repository.(*Repository).savePacker
	/tmp/restic-build-753916405/src/restic/repository/packer_manager.go:121
restic/repository.(*Repository).Flush
	/tmp/restic-build-753916405/src/restic/repository/repository.go:247
restic/archiver.(*Archiver).Snapshot
	/tmp/restic-build-753916405/src/restic/archiver/archiver.go:732
main.runBackup
	/tmp/restic-build-753916405/src/cmds/restic/cmd_backup.go:492
main.glob..func2
	/tmp/restic-build-753916405/src/cmds/restic/cmd_backup.go:38
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-753916405/src/github.com/spf13/cobra/command.go:631
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-753916405/src/github.com/spf13/cobra/command.go:710
github.com/spf13/cobra.(*Command).Execute

## Steps to reproduce the behavior

run backup command on one of above mentioned backends

## Do you have any idea what may have caused this?

No idea yet, but other commands like init, snapshots, listdir are working fine on both backends

**Comment by fd0** [comment]
Thanks for the report. The problem with Hetzner is that they're using a version of proftpd which has a bug that causes connections to be aborted after a while when many concurrent write requests are . It's already known and tracked in #353, here's a more in-depth discussion: https://github.com/restic/restic/issues/665#issuecomment-259395915

The Strato error is something different. Can you please try again while [writing a debug log](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)? Please have a look at the log before uploading it anywhere since it may contain sensitive data (at least the file and directory names).

**Comment by dirk777** [comment]
Please find the full log here: https://expirebox.com/download/699ff0987c3a18f1a7bdb3dd30f884a7.html

Here are the last lines, where the error message occurs:
```
2017/05/31 06:46:29 repository/index.go:140	repository.(*Index).Lookup	135	id eda8d0e6 not found
2017/05/31 06:46:29 repository/master_index.go:38	repository.(*MasterIndex).Lookup	135	id eda8d0e6 not found in any index
2017/05/31 06:46:29 repository/repository.go:169	repository.(*Repository).SaveAndEncrypt	135	save id eda8d0e6 (data, 717544 bytes)
2017/05/31 06:46:29 repository/packer_manager.go:67	repository.(*packerManager).findPacker	161	searching packer for 3026 bytes
2017/05/31 06:46:29 repository/packer_manager.go:70	repository.(*packerManager).findPacker	161	found packer <Packer 13 blobs, 1484131 bytes>
2017/05/31 06:46:29 repository/packer_manager.go:123	repository.(*Repository).savePacker	130	Save(<data/12a21c03a9>) error: OpenFile: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
2017/05/31 06:46:29 archiver/archiver.go:105	archiver.(*Archiver).Save	130	Save(data, 815c9649): error OpenFile: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
2017/05/31 06:46:29 repository/repository.go:196	repository.(*Repository).SaveAndEncrypt	161	pack is not full enough (1487157 bytes)
2017/05/31 06:46:29 repository/packer_manager.go:102	repository.(*packerManager).insertPacker	161	2 packers
2017/05/31 06:46:29 archiver/archiver.go:109	archiver.(*Archiver).Save	161	Save(data, 727ff615): new blob
2017/05/31 06:46:29 archiver/archiver.go:186	archiver.updateNodeContent	103	checking size for file /Users/test/Downloads/restic/doc/development.rst
2017/05/31 06:46:29 archiver/archiver.go:195	archiver.updateNodeContent	103	  adding blob 727ff615, 2994 bytes
2017/05/31 06:46:29 archiver/archiver.go:202	archiver.updateNodeContent	103	SaveFile("/Users/test/Downloads/restic/doc/development.rst"): 1 blobs
2017/05/31 06:46:29 archiver/archiver.go:322	archiver.(*Archiver).fileWorker	103	   processed restic/doc/development.rst, 1 blobs
2017/05/31 06:46:29 archiver/archiver.go:263	archiver.(*Archiver).fileWorker	103	got job {/Users/test/Downloads restic/doc/images/aws_s3/12_policy_permissions_done.png 0xc4201924e0 <nil> 0xc4222cdce0 <nil>}
```

**Comment by middelink** [comment]
I discovered the same problem with Hetzners storagebox offering, using proftp 1.3.5b, and filed a support ticket asking them to upgrade. Not sure it will work as it looks like those boxes are some appliance...

Perhaps others afflicted with the same issue can file similar support requests with them? Together we stand stronger ^^

**Comment by middelink** [comment]
From Hetzner:

>Dear Mrs. Middelink,
>
>we would like to upgrade to the latest 1.3.6 version of Proftpd but unfortunately is the update not jet available for our used operating system. The newest currently available version is 1.3.5d which includes the written SSH bug #4288.
>
>As soon as the 1.3.5e or 1.3.6 version is available we will test it and deploy it at all storage server. Kindly excuse any inconvenience caused by that.

**Comment by dirk777** [comment]
fd0, which further information do you need?

**Comment by fd0** [comment]
The Hetzner case is solved, it's caused by their version of proftpd.

The strate case puzzles me, but I have a hunch what's maybe going on here. Do you know what they are using as the sftp server implementation? Did it work with a previous version of restic?

You can try if patching restic as follows works:
```patch
diff --git a/src/restic/backend/sftp/sftp.go b/src/restic/backend/sftp/sftp.go
index 3eedfa7..79998ab 100644
--- a/src/restic/backend/sftp/sftp.go
+++ b/src/restic/backend/sftp/sftp.go
@@ -276,7 +276,7 @@ func (r *SFTP) Save(h restic.Handle, rd io.Reader) (err error) {
        filename := r.Filename(h)
 
        // create new file
-       f, err := r.c.OpenFile(filename, os.O_CREATE|os.O_EXCL|os.O_WRONLY)
+       f, err := r.c.OpenFile(filename, os.O_CREATE|os.O_WRONLY)
        if r.IsNotExist(errors.Cause(err)) {
                // create the locks dir, then try again
                err = r.mkdirAll(r.Dirname(h), backend.Modes.Dir)
```

**Comment by dirk777** [comment]
it works still very reliable with restic 0.5.0

here are the verbose of sftp command to strato's hidrive:

```
sftp -vvv sftp.hidrive.strato.com
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/myuser/.ssh/config
debug1: /Users/myuser/.ssh/config line 8: Applying options for sftp.hidrive.strato.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to sftp.hidrive.strato.com [85.214.3.70] port 22.
debug1: Connection established.
debug1: identity file /Users/myuser/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/myuser/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_3.7.1p2
debug1: match: OpenSSH_3.7.1p2 pat OpenSSH_3.* compat 0x01000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to sftp.hidrive.strato.com:22 as 'userid'
debug3: hostkeys_foreach: reading file "/Users/myuser/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /Users/myuser/.ssh/known_hosts:12
debug3: load_hostkeys: loaded 1 keys from sftp.hidrive.strato.com
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-dss
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-cbc,3des-cbc,blowfish-cbc
debug2: kex_parse_kexinit: aes128-cbc,3des-cbc,blowfish-cbc
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-sha1-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-sha1-96
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug1: kex: server->client aes128-cbc hmac-sha1 none
debug1: kex: client->server aes128-cbc hmac-sha1 none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<7680<8192) sent
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug2: bits set: 1017/2048
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-rsa SHA256:FEq+NKLciheDUUoeKGUxofLtx59sHMdxNai/I2zwBOk
debug3: hostkeys_foreach: reading file "/Users/myuser/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /Users/myuser/.ssh/known_hosts:12
debug3: load_hostkeys: loaded 1 keys from sftp.hidrive.strato.com
debug3: hostkeys_foreach: reading file "/Users/myuser/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /Users/myuser/.ssh/known_hosts:12
debug3: load_hostkeys: loaded 1 keys from 85.214.3.70
debug1: Host 'sftp.hidrive.strato.com' is known and matches the RSA host key.
debug1: Found key in /Users/myuser/.ssh/known_hosts:12
debug2: bits set: 1039/2048
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /Users/myuser/.ssh/id_rsa (0x..............), explicit
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/myuser/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp SHA256:i3Vx6Yg31DWXWcqf0CAC2gqLSNT5qvTdF2dGMXJUk0Q
debug3: sign_and_send_pubkey: RSA SHA256:i3Vx6Yg31DWXWcqf0CAC2gqLSNT5qvTdF2dGMXJUk0Q
debug1: Authentication succeeded (publickey).
Authenticated to sftp.hidrive.strato.com ([85.214.3.70]:22).
debug2: fd 5 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Entering interactive session.
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env TMPDIR
debug3: Ignored env SSH_CLIENT
debug3: Ignored env RESTIC_PASSWORD
debug3: Ignored env SSH_TTY
debug3: Ignored env USER
debug3: Ignored env MAIL
debug3: Ignored env PATH
debug3: Ignored env PWD
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env LOGNAME
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env DEBUG_LOG
debug3: Ignored env _
debug3: Ignored env __CF_USER_TEXT_ENCODING
debug1: Sending subsystem: sftp
debug2: channel 0: request subsystem confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: subsystem request accepted on channel 0
debug2: Remote version: 3
Connected to sftp.hidrive.strato.com.
debug3: Sent message fd 3 T:16 I:1
debug3: SSH_FXP_REALPATH . -> / size 0 
```

**Comment by fd0** [comment]
Ok, so they're using OpenSSH. We don't know what the sftp server implementation on their side is. Whan maybe happens here is that restic tries to create a new file with the flag `O_EXCL` and the server responds with a "Permission Denied" error. This flag instructs make the create file operation fail if the file already exists. Maybe their sftp server implementation doesn't accept it?

Can you try with the patch please, so we can see if my guess was right?

**Comment by dirk777** [comment]
Unfortunately the error still occurs in the same way after patching sftp.go The function header of the 0.6.1 looks a little bit different, so I just put out the `O_EXCL` flag in the line `f, err := r.c.OpenFile(filename, os.O_CREATE|os.O_EXCL|os.O_WRONLY)` compiled the code with go 1.8.3 and tested.

**Comment by fd0** [comment]
Is there a chance you can (temporarily) give me access to a HiDrive account so I can debug this? I'm also available on `irc.freenode.net, #restic`...

**Comment by fd0** [comment]
Could you please list the directory, like this?
```
$ sftp.hidrive.strato.com
sftp> pwd
[...]
sftp> ls -al
[...]
```

Maybe the path is wrong?

**Comment by dirk777** [comment]
```
Connected to sftp.hidrive.strato.com.
sftp> pwd
Remote working directory: /
sftp> ls -al
dr-x------    4 1000     1100            4 Mar  1 08:03 .
dr-x------    4 1000     1100            4 Mar  1 08:03 ..
drwx------    2 1000     1100            2 Mar  1 08:03 public
dr-x------    3 1000     1100            3 Mar  1 08:10 users
```

**Comment by fd0** [comment]
Hm, doesn't look bad. I have no idea what's going on here, and I won't spend any more time guessing. Thanks for understanding!

**Comment by dirk777** [comment]
no problem, thx for digging in so far!
